### ISSUE TITLE
"ellipse = T" would cause error for venns with less than 4 sets

### ISSUE THREAD

**Issue by mmahmoudian** [dusadrian/venn#11]
## The issue

When the argument `ellipse = T` is provided for lists with less than 3 sets, the following error is produced and only the circles are drawn:

> Error in text.default(icoords, labels = ilabels, cex = ilcs) : 
>   no coordinates were supplied

For example, this code will break and commenting the ellipse line would make it to work:

```r
set.seed(12345)
venn(list(a = sample(x = letters, size = 10),
          b = sample(x = letters, size = 10)),
     ellipse = T
)
```

same goes for a set of 3:

```r
set.seed(12345)
venn(list(a = sample(x = letters, size = 10),
          b = sample(x = letters, size = 10),
          c = sample(x = letters, size = 10),
     ellipse = T
)
```

and this will work:

```r
set.seed(12345)
venn(list(a = sample(x = letters, size = 10),
          b = sample(x = letters, size = 10),
          c = sample(x = letters, size = 10),
          d = sample(x = letters, size = 10)),
     ellipse = T
)
```

**Comment by mmahmoudian** [comment]
I believe the error is generated by [the line 433 of venn.R](https://github.com/dusadrian/venn/blob/91be160965fc4e46337c33d503004cc4c5c22666/R/venn.R#L433);

https://github.com/dusadrian/venn/blob/91be160965fc4e46337c33d503004cc4c5c22666/R/venn.R#L433

which is because of [the line 425 of venn.R](https://github.com/dusadrian/venn/blob/91be160965fc4e46337c33d503004cc4c5c22666/R/venn.R#L425):

https://github.com/dusadrian/venn/blob/91be160965fc4e46337c33d503004cc4c5c22666/R/venn.R#L425

**Comment by dusadrian** [comment]
Hello @mmahmoudian,

Yes indeed, and the solution is to simply prevent that from happening (now on lines 481:483).
I did something like that in lines 163:165, and thought to have put it away but that was only happening within the if() clause on line 98.

Thanks, fixed now in the latest dev version,
Adrian
