### ISSUE TITLE
Modify Font size

### ISSUE THREAD

**Issue by rukawa917** [dusadrian/venn#12]
May I know how I can modify the font sizes?

**Comment by mmahmoudian** [comment]
@rukawa917 can you specify which part would you change? As far as I can remember there is an argument to modify the font size for numbers inside the venn but no way to modify the text size of labels and title. You can change the title size if you use the `title()` from base R.

**Comment by rukawa917** [comment]
@mmahmoudian I was wondering about the font size of the numbers inside the venn diagrams (I'm new to R XD)

**Comment by mmahmoudian** [comment]
@rukawa917 No worries, we all have been new to R at some point ;)

By changing `ilcs` argument you can change the numbers (default is 0.6), and by changing `sncs` you can change the label size (default is 0.85)

You can find the manual here:

https://cran.r-project.org/web/packages/venn/venn.pdf#page5

**Comment by rukawa917** [comment]
@mmahmoudian Thank you very much!

**Comment by dusadrian** [comment]
Dear Chris and Mehrad,

I am answering late having had an end of the year leave.
Indeed, thanks very much Mehrad for being so attentive to the package venn issues, and if I understand this right there is still a need to modify the text size for the labels.
That is a good suggestion and will probably introduce a new argument in a future version.

Best wishes for the new year,
Adrian

**Comment by mmahmoudian** [comment]
@dusadrian
> if I understand this right there is still a need to modify the text size for the labels.

I don't think there is much to add since according to the documentation changing `sncs` does change the label size (I haven't tried it recently to know if it works though)

> thanks very much Mehrad for being so attentive to the package venn issues

My pleasure 😊. Happy new year to you too and wish you a fruitful year 🍻
