### ISSUE TITLE
label for the venn diagrams

### ISSUE THREAD

**Issue by sajfb** [dusadrian/venn#19]
Is there any way to add titles to these Venn diagrams?

I used the `main` object of the plot function of the R, but half of the characters are out of the Venn plot margins.

**Comment by sajfb** [comment]
I used this command to add labels and it worked:

```
mtext("string", line = -1.5)
```

**Comment by mmahmoudian** [comment]
@sajfb  In general, the `mtext()` is meant for other usecases, you are better if with `title()` as is [mentioned before](https://github.com/dusadrian/venn/issues/5#issuecomment-810423433)

Additionally, this is duplicate of #5 and #14 .

Also, 9 months ago [in another comment](https://github.com/dusadrian/venn/issues/14#issuecomment-1150401637) @dusadrian had mentioned that:

> you can actually provide the arguments "main" and "line" to function venn() via the three dots ... argument, just like you would provide the "main" argument to the base function plot()]()
