### ISSUE TITLE
How to color particular zone

### ISSUE THREAD

**Issue by mmahmoudian** [dusadrian/venn#23]
## The problem

I want to color some specific zones of the venn diagram.  For instance in the following venn I want to only highlight the `(B+C)-A`:

![image](https://github.com/dusadrian/venn/assets/390889/2f9252db-e34a-4eeb-b97f-9dc1b4008537)

I thought of using zcolor and give it a vector of length equal to all the available zones in the venn

```r
set.seed(12345)

tmp_list <- list(first = sample(x = letters, size = 20, replace = FALSE),
                 second = sample(x = letters, size = 20, replace = FALSE),
                 third = sample(x = letters, size = 20, replace = FALSE))
venn_design <- venn(tmp_list)
tmp_col <- rep.int(x = NA, times = nrow(venn_design))
tmp_col[match("second:third", row.names(venn_design))] <- "red"
venn(tmp_list, zcolor = tmp_col)
```

but it does not work because I think the zcolor expects colors for sets and not zones.

After reading the README page, I had an idea, but it seems that does not work due to lack of grouping. For instance I want to color only the zones that I marked:

```r
venn("A + B~C", snames = "A, B, C, D")
venn("(A+B) ~ (C+D)", snames = "A, B, C, D")
venn("[A+B] ~ [C+D]", snames = "A, B, C, D")
venn("{A+B} ~ {C+D}", snames = "A, B, C, D")
```

![image](https://github.com/dusadrian/venn/assets/390889/e21c8fb3-49db-4e03-96be-fe43a252f8eb)

What solution do you suggest?

**Comment by dusadrian** [comment]
Hi @mmahmoudian,

I wonder what would be wrong with:
```r
venn("~ABC")
```

<img width="381" alt="ABnotC" src="https://github.com/dusadrian/venn/assets/915070/df4ff91e-afd0-4bb8-94a6-38422698e31a">

This corresponds to your own highlighted (first) zone, which is something different than "(B+C)-A".
Mine should be read as: the intersection between B and C and not A, whereas your expression is: the intersection between not A and the union between B and C.

As for the second diagram, this seems to solve:
```r
venn("A~B~C~D + AB~C~D + ~AB~C~D")
```
<img width="380" alt="Second" src="https://github.com/dusadrian/venn/assets/915070/821b43a5-d67e-4baa-b669-4e5377ef3110">

There are other ways, for instance the later is equivalent to:
```r
venn("1000 + 1100 + 0100")
```
which is a slightly more compact way of saying the same thing in Boolean notation where 1 is presence and 0 is absence.

Is this what you're looking for?

**Comment by mmahmoudian** [comment]
Thanks for re reply. To be fair I have never used this notation. My real use-case is that I have a list with named items (names that are text, such as `Ctrl`, `Case1`, `Case2`, `Case3`. So I don't know how the the `AB~C` would work considering that there is no separator between names. So basically it boils down to two questions:
1. How can I use a named list (like the example above) and yet use the `AB~C` format
2. How can I use names that are longer than one character when using `AB~C`

**Comment by dusadrian** [comment]
The treatment of these so-called "SOP" expressions is done by package `admisc` (the only one this package imports).
If the set names are longer than 1 character, this SOP expression would still be valid:
```r
library(admisc)
translate("Ctrl*~Case1*~Case2*~Case3 + Ctrl*Case1*~Case2*~Case3 + ~Ctrl*Case1*~Case2*~Case3")

                             Case1 Case2 Case3 Ctrl
Ctrl*~Case1*~Case2*~Case3      0     0     0    1  
Ctrl*Case1*~Case2*~Case3       1     0     0    1  
~Ctrl*Case1*~Case2*~Case3      1     0     0    0
```

It even works without the star signs, if you provide the set names (with the added value it preserves the ordering of the set names you specify):

```r
translate(
    "Ctrl~Case1~Case2~Case3 + CtrlCase1~Case2~Case3 + ~CtrlCase1~Case2~Case3",
    snames = "Ctrl, Case1, Case2, Case3"
)

                          Ctrl Case1 Case2 Case3
Ctrl~Case1~Case2~Case3     1     0     0     0  
CtrlCase1~Case2~Case3      1     1     0     0  
~CtrlCase1~Case2~Case3     0     1     0     0
```

I am afraid the argument "zcolor" can only be used for the sets themselves (as a vector of colours of length equal to the number of sets), or for the specified intersections in the SOP expression. It could in principle be used for individual intersections, as a vector of length equal to the number of all possible intersections, but I cannot really think of a practical example of where this might be useful.

Or at least why would this complicated way would be preferred over the much more simple SOP expressions.

**Comment by mmahmoudian** [comment]
Thanks for your reply.

> It could in principle be used for individual intersections, as a vector of length equal to the number of all possible intersections, but I cannot really think of a practical example of where this might be useful.

It is actually useful for the use-case I have at the moment. I have four sets of genes (in form of a list) and I am interested only a particular intersection, so I want to use a particular color for that zone, and leave the rest as default (white background). This is useful for preparing the venn for a journal article or presentation.

To explain in more details, imagine I have the following list:

```r
set.seed(12345)

tmp_list <- list(first  = sample(x = letters, size = 20, replace = FALSE),
                 second = sample(x = letters, size = 20, replace = FALSE),
                 third  = sample(x = letters, size = 20, replace = FALSE))
```

and I want to have a venn (with the numbers) and highlight the background of that particular intersection:
 
```r
# get the intersections
venn_design <- venn(tmp_list)
# create a vector of NAs ith the correct length
tmp_col <- rep.int(x = NA, times = nrow(venn_design))
# change the value of the exact intersection using the notation used in the venn output matrix
tmp_col[match("second:third", row.names(venn_design))] <- "red"
# apply the color
venn(tmp_list, zcolor = tmp_col)
```

Of course the code above does not work, but it also does not produce any errors

I then tried the following hoping that I can get the numbers there:

```r
# get the intersections
venn_design <- venn(tmp_list)

venn(x = "second*third ~ first",
     snames = "first, second, third",
     counts = venn_design$counts)
```

but it does not add the numbers:

![image](https://github.com/dusadrian/venn/assets/390889/9c275cc8-4323-4e39-a9c8-4f0303431114)


So here are two questions:
1. is it a bug that the `counts` argument value are ignored?
2. is there a way to pull this off in an easier way? (this is impractical because I have to plot one venn before to get the count in the exact order that is required, so that I can plot the venn that I'm looking for)

**Comment by dusadrian** [comment]
Not a bug, since `counts` is no longer a formal argument of the main function `venn()`.
Instead, you can use the counts for the intersection labels:

```r
venn(x = "second*third*~first",
     snames = "first, second, third",
     ilabels = venn_design$counts)
```
<img width="440" alt="venn1" src="https://github.com/dusadrian/venn/assets/915070/f99f0351-f0b3-4e73-bd90-73069cd8b3b0">


And, if specifying a different color for this "zone":
```r
venn(x = "second*third*~first",
     snames = "first, second, third",
     ilabels = venn_design$counts
     zcolor = "red")
```
<img width="438" alt="venn2" src="https://github.com/dusadrian/venn/assets/915070/4940590b-4f21-4aab-a115-42d6853f5cb1">

Do notice however that your SOP expression `second*third ~ first` (despite package `admisc` figuring it out) is not syntactically correct.

Since you are using the star sign `*`, it should either be `second*third*~first` or `secondthird~first` (the later is a bit confusing but if specifying the set names the package `admisc` is doing a good job identifying them).

Also, the tilde sign `~` is used to indicate a negation, and there should be no space from the set name: `~first`. Otherwise, separating it from the set name can be confusing, as in: `second*third ~ first` which looks more like a sort of an equation, or an R formula, than a proper SOP expression.

**Comment by mmahmoudian** [comment]
When I run the following:

```r
set.seed(12345)

tmp_list <- list(first  = sample(x = letters, size = 20, replace = FALSE),
                 second = sample(x = letters, size = 20, replace = FALSE),
                 third  = sample(x = letters, size = 20, replace = FALSE))
# get the intersections
venn_design <- venn(tmp_list)
# plot a new venn with the counts and highlighted region
venn(x = "second*third*~first",
     snames = "first, second, third",
     ilabels = venn_design$counts)
```

I get the following error:

```
Warning message:
In if (ilabels | counts & !is.null(cts)) { :
  the condition has length > 1 and only the first element will be used
```

And this is what I get (counts are not plotted):

![image](https://github.com/dusadrian/venn/assets/390889/7380e5d1-fb8e-4061-90e2-d7712a859dd5)



I have the venn_1.11 installed and am using R version 4.1.2.

**Update:**  It seems the issue [is addressed](https://github.com/dusadrian/venn/commit/496cc89e25e671a7b69626b954d5befbcd550563#diff-34c15b887bb5119d0a89f3ed0bab58b08610ed6df4977bf5afa6bdaca0bc612bL542-R569) by the 496cc89e25e671a7b69626b954d5befbcd550563 which was merged 9 months ago is not published to CRAN yet.
Is there anything I can do to help preparing the package for CRAN?

**Comment by dusadrian** [comment]
Right, for the moment you could install the latest development version and see it the warning persists. My guess is that fix from 9 months ago will solve this issue as well.

I could in principle release a new CRAN version, I am just waiting for more problems to fix or new features to add. In the meantime, I see no problem at all installing a GitHub development version (it is its very purpose, after all).

**Comment by mmahmoudian** [comment]
I think this can be closed, but I personally would rather being able to pass one of the following to the `zcolor`:
- a vector with length equal to number of zones in the venn with the order than venn processes the list and is in the rownames of in the invisible output of `venn::venn()`
- a named vector so that the name matches the zone naming convention of `venn::venn()` like `zcolor = c(`A:B`= "salmon")`

With the current version, I have to run venn twice, once to feed it to `counts` and once for plotting. The worst part is that there is no way to suppress plotting, so the first venn call cannot be done while writing to `pdf()`.

Anyways, thanks for the reply and guiding me on how to pull this off.

**Comment by dusadrian** [comment]
With the new function, this is now better addressed as:

```r
venn(x = "second*third*~first",
     snames = "first, second, third",
     ilabels = extractInfo(tmp_list)$counts)
```

Hopefully, this is in line with your intended output.
