### ISSUE TITLE
Error when setting colors with ggplot=TRUE

### ISSUE THREAD

**Issue by DanChaltiel** [dusadrian/venn#3]
Hi Adrian,

Thank you very much for this great package.

I am very fond of `ggplot2` but I'm facing an error when using your function with `ggplot=TRUE`.

Indeed, it seems that it is not possible to have anything else than black & white plots in this case:

```r
x <- as.data.frame(matrix(sample(0:1, 150, replace = TRUE), ncol = 5))
venn(x, zcolor = "style")
venn(x, zcolor = "style", ggplot=TRUE)
#Error: Aesthetics must be either length 1 or the same as the data (3065): fill

venn(x, zcolor = rainbow(7), ggplot=TRUE)
#Error: Aesthetics must be either length 1 or the same as the data (3065): fill

venn(x, zcolor = "red", ggplot=TRUE)
#Error: Aesthetics must be either length 1 or the same as the data (3065): fill
```

Here is the stack trace of the error:

> 
> ```
> > rlang::last_error()
> <error/rlang_error>
> Aesthetics must be either length 1 or the same as the data (3065): fill
> Backtrace:
>   1. (function (x, ...) ...
>   2. ggplot2:::print.ggplot(x)
>   4. ggplot2:::ggplot_build.ggplot(x)
>   5. ggplot2:::by_layer(function(l, d) l$compute_geom_2(d))
>   6. ggplot2:::f(l = layers[[i]], d = data[[i]])
>   7. l$compute_geom_2(d)
>   8. ggplot2:::f(..., self = self)
>   9. self$geom$use_defaults(data, self$aes_params, modifiers)
>  10. ggplot2:::f(..., self = self)
>  11. ggplot2:::check_aesthetics(params[aes_params], nrow(data))
> Run `rlang::last_trace()` to see the full context.
> > rlang::last_trace()
> <error/rlang_error>
> Aesthetics must be either length 1 or the same as the data (3065): fill
> Backtrace:
>      x
>   1. +-(function (x, ...) ...
>   2. \-ggplot2:::print.ggplot(x)
>   3.   +-ggplot2::ggplot_build(x)
>   4.   \-ggplot2:::ggplot_build.ggplot(x)
>   5.     \-ggplot2:::by_layer(function(l, d) l$compute_geom_2(d))
>   6.       \-ggplot2:::f(l = layers[[i]], d = data[[i]])
>   7.         \-l$compute_geom_2(d)
>   8.           \-ggplot2:::f(..., self = self)
>   9.             \-self$geom$use_defaults(data, self$aes_params, modifiers)
>  10.               \-ggplot2:::f(..., self = self)
>  11.                 \-ggplot2:::check_aesthetics(params[aes_params], nrow(data))
> ```

And here is my session info:

> ```
> > sessionInfo()
> R version 4.0.1 (2020-06-06)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18362)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
> [4] LC_NUMERIC=C                   LC_TIME=French_France.1252    
> 
> attached base packages:
> [1] grid      stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] venn_1.9            ggVennDiagram_0.3.3 VennDiagram_1.6.20  futile.logger_1.4.3
>  [5] forcats_0.5.0       stringr_1.4.0       dplyr_1.0.2         purrr_0.3.4        
>  [9] readr_1.3.1         tidyr_1.1.2         tibble_3.0.3        ggplot2_3.3.2      
> [13] tidyverse_1.3.0    
> 
> loaded via a namespace (and not attached):
>  [1] crosstable_0.1.5     fs_1.4.1             sf_0.9-6             usethis_1.6.1       
>  [5] lubridate_1.7.9      devtools_2.3.0       httr_1.4.1           rprojroot_1.3-2     
>  [9] tools_4.0.1          backports_1.1.7      utf8_1.1.4           R6_2.4.1            
> [13] KernSmooth_2.23-17   nortest_1.0-4        DBI_1.1.0            colorspace_1.4-1    
> [17] withr_2.2.0          tidyselect_1.1.0     prettyunits_1.1.1    processx_3.4.2      
> [21] compiler_4.0.1       cli_2.0.2            rvest_0.3.5          formatR_1.7         
> [25] flextable_0.5.10     xml2_1.3.2           officer_0.3.14       desc_1.2.0          
> [29] labeling_0.3         scales_1.1.1         checkmate_2.0.0      classInt_0.4-3      
> [33] callr_3.4.3          systemfonts_0.2.2    digest_0.6.25        rmarkdown_2.3       
> [37] htmltools_0.5.0      base64enc_0.1-3      pkgconfig_2.0.3      sessioninfo_1.1.1   
> [41] dbplyr_1.4.4         rlang_0.4.7          readxl_1.3.1         rstudioapi_0.11     
> [45] farver_2.0.3         generics_0.0.2       jsonlite_1.6.1       zip_2.1.1           
> [49] magrittr_1.5         Matrix_1.2-18        Rcpp_1.0.4.6         munsell_0.5.0       
> [53] fansi_0.4.1          ggpolypath_0.1.0     gdtools_0.2.2        lifecycle_0.2.0     
> [57] stringi_1.4.6        pkgbuild_1.0.8       blob_1.2.1           crayon_1.3.4        
> [61] lattice_0.20-41      splines_4.0.1        haven_2.3.1          hms_0.5.3           
> [65] knitr_1.29           ps_1.3.3             pillar_1.4.4         uuid_0.1-4          
> [69] admisc_0.10          pkgload_1.1.0        futile.options_1.0.1 reprex_0.3.0        
> [73] glue_1.4.2           evaluate_0.14        packrat_0.5.0        lambda.r_1.2.4      
> [77] data.table_1.12.8    remotes_2.1.1        modelr_0.1.8         vctrs_0.3.4         
> [81] testthat_2.3.2       cellranger_1.1.0     gtable_0.3.0         assertthat_0.2.1    
> [85] xfun_0.16            broom_0.7.0          e1071_1.7-3          survival_3.1-12     
> [89] class_7.3-17         memoise_1.1.0        units_0.6-7          ellipsis_0.3.1    
> ```

Don't hesitate to ask for more details.

Dan

**Comment by dusadrian** [comment]
Hi Dan,

Will have to find some time to look at this, for the moment I am quite squeezed. Not exactly a ggplot2 expert, myself. The culprit seems to be the way venn() builds the object, while the error and the traceback are generated by the ggplot2 package.

I'll have to learn more about how to build these ggplot2 objects, and the solution will surely reveal itself.

Best,
Adrian

**Comment by dusadrian** [comment]
Should be fixed now, thanks for reporting.
