### ISSUE TITLE
Why there is a 0 at left-top corner?

### ISSUE THREAD

**Issue by xiekunwhy** [dusadrian/venn#30]
Hi,

I found that there is always a 0 at left-top corner of the venn plot, how to remove it.

![image](https://github.com/dusadrian/venn/assets/17738229/ce175859-1330-446d-9f15-dc9e4ba7c743)

Best,
Kun

**Comment by dusadrian** [comment]
Hello Kun,

This is deeply embedded in the code, and I would not create a separate argument just to get rid of a 0 sign.
You can however generate your own intersection labels, for instance:

```r
nofsets <- 5
customlabels <- apply(
    sapply(
        rev(seq(nofsets)),
        function(x) {
            rep.int(
                c(sapply(0:1, function(y) rep.int(y, 2^(x - 1)))),
                2^nofsets / 2^x
            )
        }
    ),
    1,
    function(x) {
        paste(which(x == 1), collapse = "")
    }
)

venn(
    5,
    ilabels = customlabels,
    snames = c("KOG", "GO", "NR", "SwissProt", "KEGG"),
    zcolor = "style"
)
```
<img width="683" alt="Screenshot 2024-06-06 at 16 49 59" src="https://github.com/dusadrian/venn/assets/915070/64446c0f-d115-4867-b3e4-6883c4690e76">

**Comment by mmahmoudian** [comment]
@xiekunwhy 
Because that rectangle around the the plot is also a set that contains every other set you have. Think about it as the "universe" that contains certain sets. Because in your example there is no item that is in the universe alone (not being part of any other sets), the value is zero.

The way I bypass it is to provide the `venn()` a list of elements.

```r
venn(list(a = letters[1:10],
          b = letters[5:15]),
     ilabels = "counts",
     ilcs = 1.2,
     zcolor = c("blue", "red"))
```

![image](https://github.com/dusadrian/venn/assets/390889/2c12729d-a8b5-4007-be17-5733f0aca900)

**Comment by xiekunwhy** [comment]
Thank you all.

@dusadrian solved my problem.

Best,
Kun

**Comment by xiekunwhy** [comment]
I found this problem when install venn package in R 4.3, the plot always the same when there are 5 elements in a list (just 1 2 3 4 5 in plot, not plotting real data).

**Comment by mmahmoudian** [comment]
@xiekunwhy 

> I found this problem when install venn package in R 4.3, the plot always the same when there are 5 elements in a list (just 1 2 3 4 5 in plot, not plotting real data).

Can you provide an example code that shows the issue?

**Comment by xiekunwhy** [comment]
It is not R 4.3 problem, just machine problem, the result is normal on some machine but abnormal on others. Here is the data
[venn.rtab.xls.gz](https://github.com/user-attachments/files/15949263/venn.rtab.xls.gz)

and here is the codes
```
Rscript ggvenn3.r venn.rtab.xls venn.r.tab

codes in ggvenn3.r

args <- commandArgs(TRUE)
infile = args[1]
outpfx = args[2]
library(venn)
set.seed(12345)
vdat <- read.table(infile, header = F, stringsAsFactors = F)
ids <- unique(vdat$V1)
df1 <- list()
for (id in ids) {
  print(id)
  df1[[id]] <- unique(vdat[vdat$V1 == id,][,2])
}
print(str(df1))
pdf(file = paste0(outpfx, ".pdf"), width = 5, height = 5)
venn(df1, ilabels = TRUE, zcolor = "style")
dev.off()
png(filename = paste0(outpfx, ".png"), width = 5, height = 5, res = 300, units = "in")
venn(df1, ilabels = TRUE, zcolor = "style")
dev.off()

```



```
> sessionInfo()
Warning: ‘timedatectl’ indicates the non-existent timezone name ‘n/a’
Warning: Your system is mis-configured: ‘/etc/localtime’ is not a symlink
Warning: It is strongly recommended to set envionment variable TZ to ‘Asia/Chongqing’ (or equivalent)
R version 4.3.2 (2023-10-31)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /public2/home/sl_qybio/sl_qybio/miniforge3/envs/R43/lib/libopenblasp-r0.3.25.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

time zone: Asia/Chongqing
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] venn_1.12

loaded via a namespace (and not attached):
[1] compiler_4.3.2 admisc_0.35   

```

**Comment by mmahmoudian** [comment]
@xiekunwhy can you also share the correct output and the problematic output as well (one example of each)

**Comment by xiekunwhy** [comment]
Here is the correct one
![venn machine1 correct](https://github.com/dusadrian/venn/assets/17738229/9db47b1a-381c-47a3-9e8e-0a069148a7b3)

and here is the wrong one
![venn machine2 wrong](https://github.com/dusadrian/venn/assets/17738229/9e952a8c-23a7-46c2-b651-77ef857ebedc)

**Comment by xiekunwhy** [comment]
It is always normal when running venn in R 3.6.3

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-conda-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /public2/home/sl_qybio/sl_qybio/miniforge3/envs/R36/lib/libopenblasp-r0.3.27.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3

```

and get wrong results on some machines when R >= 4.0

**Comment by dusadrian** [comment]
If the code works on some machine but not on others, most likely this is due to different versions of the package `venn` installed on separate machines.

The correct image is created using the argument `ilabels = "counts"` instead of `ilabels = TRUE`.

Please note the argument `ilabels` has changed its behavior over time, with examples and explanations in the help file.

@xiekunwhy please note this is a different topic than the current "0 at left-top corner".

**Comment by xiekunwhy** [comment]
Thank you very much, ilabels = TRUE stucked me several days.
All machine worked when I change ilabels = TRUE to ilabels = "counts".
