### ISSUE TITLE
Is there a way to display 0 if the particular intersection does not have any common values ?

### ISSUE THREAD

**Issue by rabbit258** [dusadrian/venn#31]
Assume i have a Venn diagram of 6 group like this. 
﻿
![A_11FO1OQZU_)${P9O69Q Q](https://github.com/user-attachments/assets/4b9e4212-9dd1-4ffe-a35e-db992b5bb220)

Is there a way to display these blank zeros？

**Comment by dusadrian** [comment]
Yes it is possible, using the `ilabels` argument.
Have a look on the solution from [this issue](https://github.com/dusadrian/venn/issues/30), and adapt accordingly. Otherwise, we need a minimal reproducible example to further assist.

**Comment by rabbit258** [comment]
It's solved, thank you
