### ISSUE TITLE
output specific items for each section of the venn diagram

### ISSUE THREAD

**Issue by zhilongjia** [dusadrian/venn#7]
Besides plotting venn diagram, if `venn` could output the items in each section of the venn diagram will be great.

For example below, which 5 items are A set specific? which 8 items are overlapped between the a, B and C sets? returning a list containing these information will be great. Thank you.  BTW, `venn` support more than 5 sets, which is really wonderful.

![venn](https://user-images.githubusercontent.com/1230436/114719790-01f72380-9d6a-11eb-95e3-26c97a53acdf.png)

**Comment by dusadrian** [comment]
Hi Zhilong, this is already implemented:

```r
set.seed(12345)
x <- list(A = 1:20, B = 10:30, C = sample(25:50, 15))
y <- venn(x)

attr(y, "intersections")

# $C
#  [1] 38 43 40 35 47 31 34 41 48 32 49 44

# $B
# [1] 21 22 23 24 27 28 29

# $`B:C`
# [1] 25 26 30

# $A
# [1] 1 2 3 4 5 6 7 8 9

# $`A:B`
#  [1] 10 11 12 13 14 15 16 17 18 19 20
```

**Comment by zhilongjia** [comment]
I used to use `attr` to get the intersection items for `gplots::venn`. It can be used to `venn::venn` as well. Great! 

I think I do not really understand the principle behind the output of `venn::venn`, which is a `data.frame` as shown by `class` function . But using `attributes` will get what it is really.

Adding an example of `attr` in the `venn::venn` examples will be helpful to users. Thank you.

**Comment by dusadrian** [comment]
Yes, the result is a data frame (others having requested that in the past)
Almost the same thing as the intersections attribute, but instead presenting all possible intersections along with a count column. The intersections just show an additional piece of information, namely the row numbers corresponding to those counts.

```r
y

#       A B C counts
#       0 0 0      0
# C     0 0 1     12
# B     0 1 0      7
# B:C   0 1 1      3
# A     1 0 0      9
# A:C   1 0 1      0
# A:B   1 1 0     11
# A:B:C 1 1 1      0
```
