### ISSUE TITLE
Increase font size of labels when using ggplot2

### ISSUE THREAD

**Issue by thuvousc** [dusadrian/venn#8]
Hi,

I cannot increase the font size of set names and values when ggplot2 is used. Does anyone know how to fix this issue?
The code which I used is written below:

``venn(ex, box = FALSE, zcolor = col3, opacity = 0.4, borders = FALSE,
          snames = c("A", "B", "C", "D", "E", "F"),
          ilcs = 15, sncs = 25, plotsize = 30,
          ggplot = TRUE, linetype = "blank")``

Many thanks.

**Comment by dusadrian** [comment]
Solved in the latest commit, it was a bug keeping those values constant. I could not test your example though, it is not reproducible.
